apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::553490164630:role/RoboshopMySQLRea                                               der
  creationTimestamp: "2026-08-09T10:35:13Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: keshavaapp
  namespace: default
  
